# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8

xcode_sdk: iphonesimulator10.0

language: objective-c

cache: cocoapods

podfile: Example/Podfile

before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild test -workspace Example/MadSqlite.xcworkspace -scheme MadSqlite-Example -destination 'platform=iOS Simulator,name=iPhone 5,OS=10.0' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint --allow-warnings
